dist: xenial

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install tox-travis
  - python -m pip install -r requirements.test

script:
  - python setup.py bdist_wheel
  - tox
  - codecov

deploy:
  provider: pypi
  user: altendky
  password: $PYPI_PASSWORD
  on:
    branch: develop
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.7
  distributions: bdist_wheel
